services:
  - type: web
    name: my-app
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    redirects:
      - source: /*
        destination: /index.html
        type: 200
        
